// Application Constants

export const PRICING = {
    INDIVIDUAL_ASSESSMENT: 500,
    CATEGORY_COMBO: 2000,
    FULL_BUNDLE: 8000,
} as const;

export const EXAM_CONFIG = {
    DURATION_MINUTES: 50,
    MAX_VIOLATIONS: 5,
    AUTO_SAVE_INTERVAL: 10000, // 10 seconds
} as const;

export const VIOLATION_TYPES = {
    FACE_NOT_DETECTED: 'face_not_detected',
    MULTIPLE_FACES: 'multiple_faces',
    LOOKING_AWAY: 'looking_away',
    TAB_SWITCH: 'tab_switch',
    SCREEN_MINIMIZE: 'screen_minimize',
    FULLSCREEN_EXIT: 'fullscreen_exit',
    SESSION_EXIT: 'session_exit',
    COPY_PASTE: 'copy_paste',
    CONTENT_CUT: 'content_cut',
    SUDDEN_MOVEMENT: 'sudden_movement',
    GAZE_DEVIATION: 'gaze_deviation',
    VOICE_DETECTED: 'voice_detected',
    PROHIBITED_OBJECT: 'prohibited_object',
} as const;

export const SUSPICION_WEIGHTS = {
    [VIOLATION_TYPES.TAB_SWITCH]: 100,
    [VIOLATION_TYPES.FULLSCREEN_EXIT]: 100,
    [VIOLATION_TYPES.MULTIPLE_FACES]: 50,
    [VIOLATION_TYPES.PROHIBITED_OBJECT]: 40,
    [VIOLATION_TYPES.SUDDEN_MOVEMENT]: 20,
    [VIOLATION_TYPES.VOICE_DETECTED]: 25,
    [VIOLATION_TYPES.LOOKING_AWAY]: 15,
    [VIOLATION_TYPES.GAZE_DEVIATION]: 10,
    [VIOLATION_TYPES.FACE_NOT_DETECTED]: 10,
    [VIOLATION_TYPES.SCREEN_MINIMIZE]: 20,
    [VIOLATION_TYPES.COPY_PASTE]: 5,
} as const;

export const PROCTORING_CONFIG = {
    HALT_THRESHOLD: 100,
    AUDIO_LEVEL_THRESHOLD: 0.1, // Normalized volume
} as const;

export const VIOLATION_SEVERITY = {
    LOW: 'low',
    MEDIUM: 'medium',
    HIGH: 'high',
    CRITICAL: 'critical',
} as const;

export const USER_ROLES = {
    ADMIN: 'admin',
    CANDIDATE: 'candidate',
} as const;

export const QUESTION_TYPES = {
    MCQ: 'mcq',
    SCENARIO: 'scenario',
    CODING: 'coding',
} as const;

export const PURCHASE_TYPES = {
    INDIVIDUAL: 'individual',
    CATEGORY: 'category',
    BUNDLE: 'bundle',
} as const;

export const PAYMENT_STATUS = {
    PENDING: 'pending',
    COMPLETED: 'completed',
    FAILED: 'failed',
    REFUNDED: 'refunded',
} as const;

export const ATTEMPT_STATUS = {
    IN_PROGRESS: 'in_progress',
    COMPLETED: 'completed',
    TERMINATED: 'terminated',
} as const;

// Categories with their assessments
export const CATEGORIES = [
    {
        name: 'Generative AI for Business Leaders',
        slug: 'generative-ai-business-leaders',
        description: 'Strategic AI leadership, adoption, governance, and enterprise transformation.',
        subjects: [
            'AI transformation frameworks',
            'AI-driven business model innovation',
            'Enterprise AI adoption roadmap',
            'Responsible AI governance',
            'AI cost-benefit evaluation',
            'AI vendor selection strategies',
            'Automating internal workflows',
            'AI change management',
            'AI-powered decision intelligence',
            'Risk and compliance in AI',
            'AI in customer experience',
            'AI performance metrics',
        ],
        assessments: [
            'AI transformation frameworks',
            'AI-driven business model innovation',
            'Enterprise AI adoption roadmap',
            'Responsible AI governance',
            'AI cost-benefit evaluation',
            'AI vendor selection strategies',
            'Automating internal workflows',
            'AI change management',
            'AI-powered decision intelligence',
            'Risk and compliance in AI',
            'AI in customer experience',
            'AI performance metrics',
        ],
    },
    {
        name: 'Prompt Engineering and AI Automation',
        slug: 'prompt-engineering-ai-automation',
        description: 'Advanced prompting methods, agent workflows, and practical AI automation.',
        subjects: [
            'Advanced prompt structures',
            'Role-based prompting',
            'AI agents design',
            'Prompt chaining',
            'AI API integration basics',
            'Automation using AI workflows',
            'AI plus Zapier automation',
            'Creating AI SOP systems',
            'AI content validation',
            'AI hallucination control',
            'Multimodal prompting',
            'Building micro AI tools',
        ],
        assessments: [
            'Advanced prompt structures',
            'Role-based prompting',
            'AI agents design',
            'Prompt chaining',
            'AI API integration basics',
            'Automation using AI workflows',
            'AI plus Zapier automation',
            'Creating AI SOP systems',
            'AI content validation',
            'AI hallucination control',
            'Multimodal prompting',
            'Building micro AI tools',
        ],
    },
    {
        name: 'Data Engineering with Cloud Pipelines',
        slug: 'data-engineering-cloud-pipelines',
        description: 'Pipeline architecture, cloud data systems, and scalable analytics engineering.',
        subjects: [
            'Data pipeline architecture',
            'ETL vs ELT frameworks',
            'Data lakes vs warehouses',
            'Apache Spark basics',
            'Real-time data streaming',
            'Cloud storage optimization',
            'Data version control',
            'Data governance standards',
            'BigQuery fundamentals',
            'Workflow orchestration',
            'Data observability',
            'Scalable pipeline deployment',
        ],
        assessments: [
            'Data pipeline architecture',
            'ETL vs ELT frameworks',
            'Data lakes vs warehouses',
            'Apache Spark basics',
            'Real-time data streaming',
            'Cloud storage optimization',
            'Data version control',
            'Data governance standards',
            'BigQuery fundamentals',
            'Workflow orchestration',
            'Data observability',
            'Scalable pipeline deployment',
        ],
    },
    {
        name: 'UI and UX for AI Products',
        slug: 'ui-ux-ai-products',
        description: 'Design principles and interaction systems for AI-native product experiences.',
        subjects: [
            'Conversational interface design',
            'AI-first UX principles',
            'Designing for uncertainty',
            'Ethical UX patterns',
            'Voice UI fundamentals',
            'Microcopy for AI',
            'Trust-building UI elements',
            'AI feedback loops',
            'Human-AI interaction models',
            'Personalization design systems',
            'Prototyping AI dashboards',
            'UX research for AI tools',
        ],
        assessments: [
            'Conversational interface design',
            'AI-first UX principles',
            'Designing for uncertainty',
            'Ethical UX patterns',
            'Voice UI fundamentals',
            'Microcopy for AI',
            'Trust-building UI elements',
            'AI feedback loops',
            'Human-AI interaction models',
            'Personalization design systems',
            'Prototyping AI dashboards',
            'UX research for AI tools',
        ],
    },
    {
        name: 'Product Management in the AI Era',
        slug: 'product-management-ai-era',
        description: 'Product strategy, experimentation, and execution for AI-powered products.',
        subjects: [
            'AI product lifecycle',
            'MVP validation using AI',
            'Data-driven product decisions',
            'Product analytics dashboards',
            'A/B testing frameworks',
            'AI roadmap planning',
            'Stakeholder alignment',
            'Monetization strategies',
            'Product-led growth',
            'Agile AI sprint planning',
            'Feature prioritization matrices',
            'Competitive AI benchmarking',
        ],
        assessments: [
            'AI product lifecycle',
            'MVP validation using AI',
            'Data-driven product decisions',
            'Product analytics dashboards',
            'A/B testing frameworks',
            'AI roadmap planning',
            'Stakeholder alignment',
            'Monetization strategies',
            'Product-led growth',
            'Agile AI sprint planning',
            'Feature prioritization matrices',
            'Competitive AI benchmarking',
        ],
    },
    {
        name: 'Blockchain and Web3 Applications',
        slug: 'blockchain-web3-applications',
        description: 'Web3 architecture, token systems, and practical decentralized application design.',
        subjects: [
            'Smart contracts architecture',
            'Solidity basics',
            'Decentralized applications (dApps)',
            'Tokenomics design',
            'NFT utilities',
            'Web3 wallets integration',
            'DeFi ecosystem',
            'DAO governance',
            'Crypto regulations overview',
            'Blockchain scalability',
            'Layer 2 solutions',
            'Security in Web3',
        ],
        assessments: [
            'Smart contracts architecture',
            'Solidity basics',
            'Decentralized applications (dApps)',
            'Tokenomics design',
            'NFT utilities',
            'Web3 wallets integration',
            'DeFi ecosystem',
            'DAO governance',
            'Crypto regulations overview',
            'Blockchain scalability',
            'Layer 2 solutions',
            'Security in Web3',
        ],
    },
    {
        name: 'Cybersecurity and Ethical AI Security',
        slug: 'cybersecurity-ethical-ai-security',
        description: 'Security fundamentals for AI systems, cloud environments, and compliance.',
        subjects: [
            'AI system vulnerabilities',
            'Prompt injection attacks',
            'Zero-trust architecture',
            'Endpoint detection',
            'SOC operations overview',
            'Phishing simulations',
            'AI threat intelligence',
            'Cloud security posture',
            'Digital forensics basics',
            'Incident response planning',
            'Data privacy frameworks',
            'Compliance standards (GDPR basics)',
        ],
        assessments: [
            'AI system vulnerabilities',
            'Prompt injection attacks',
            'Zero-trust architecture',
            'Endpoint detection',
            'SOC operations overview',
            'Phishing simulations',
            'AI threat intelligence',
            'Cloud security posture',
            'Digital forensics basics',
            'Incident response planning',
            'Data privacy frameworks',
            'Compliance standards (GDPR basics)',
        ],
    },
    {
        name: 'Digital Branding and Creator Economy',
        slug: 'digital-branding-creator-economy',
        description: 'Brand systems, creator monetization, and audience growth analytics.',
        subjects: [
            'Personal brand positioning',
            'Creator monetization models',
            'Link-in-bio funnels',
            'Influencer commerce systems',
            'Community building strategy',
            'Short-form video psychology',
            'Platform algorithm decoding',
            'Brand storytelling',
            'Digital authority building',
            'Social proof frameworks',
            'Affiliate revenue models',
            'Audience analytics',
        ],
        assessments: [
            'Personal brand positioning',
            'Creator monetization models',
            'Link-in-bio funnels',
            'Influencer commerce systems',
            'Community building strategy',
            'Short-form video psychology',
            'Platform algorithm decoding',
            'Brand storytelling',
            'Digital authority building',
            'Social proof frameworks',
            'Affiliate revenue models',
            'Audience analytics',
        ],
    },
    {
        name: 'Financial Modeling with AI Tools',
        slug: 'financial-modeling-ai-tools',
        description: 'Finance modeling and forecasting workflows augmented by AI systems.',
        subjects: [
            'AI-based forecasting',
            'Scenario simulation',
            'Startup valuation modeling',
            'Financial dashboards',
            'Sensitivity analysis',
            'Automated reporting',
            'Cash flow prediction',
            'Investment risk modeling',
            'AI budgeting tools',
            'KPI tracking systems',
            'Business feasibility models',
            'Predictive analytics in finance',
        ],
        assessments: [
            'AI-based forecasting',
            'Scenario simulation',
            'Startup valuation modeling',
            'Financial dashboards',
            'Sensitivity analysis',
            'Automated reporting',
            'Cash flow prediction',
            'Investment risk modeling',
            'AI budgeting tools',
            'KPI tracking systems',
            'Business feasibility models',
            'Predictive analytics in finance',
        ],
    },
    {
        name: 'Sustainable Business and ESG Strategy',
        slug: 'sustainable-business-esg-strategy',
        description: 'ESG implementation, sustainability metrics, and responsible business design.',
        subjects: [
            'ESG reporting frameworks',
            'Sustainable supply chains',
            'Carbon footprint analysis',
            'Green finance fundamentals',
            'CSR strategy design',
            'Impact measurement',
            'Circular economy models',
            'SDG alignment',
            'Ethical sourcing',
            'Sustainability innovation',
            'Risk and climate adaptation',
            'Governance metrics',
        ],
        assessments: [
            'ESG reporting frameworks',
            'Sustainable supply chains',
            'Carbon footprint analysis',
            'Green finance fundamentals',
            'CSR strategy design',
            'Impact measurement',
            'Circular economy models',
            'SDG alignment',
            'Ethical sourcing',
            'Sustainability innovation',
            'Risk and climate adaptation',
            'Governance metrics',
        ],
    },
    {
        name: 'Growth Marketing and Performance Strategy',
        slug: 'growth-marketing-performance-strategy',
        description: 'Growth systems for acquisition, retention, experimentation, and scaling.',
        subjects: [
            'Conversion funnel engineering',
            'CRO frameworks',
            'Performance ad scaling',
            'Retention metrics',
            'Funnel analytics tools',
            'Landing page psychology',
            'Behavioral marketing',
            'Marketing automation',
            'Data attribution models',
            'Cohort analysis',
            'Viral loops',
            'Paid vs organic growth strategy',
        ],
        assessments: [
            'Conversion funnel engineering',
            'CRO frameworks',
            'Performance ad scaling',
            'Retention metrics',
            'Funnel analytics tools',
            'Landing page psychology',
            'Behavioral marketing',
            'Marketing automation',
            'Data attribution models',
            'Cohort analysis',
            'Viral loops',
            'Paid vs organic growth strategy',
        ],
    },
    {
        name: 'No-Code and Low-Code App Development',
        slug: 'no-code-low-code-app-development',
        description: 'Rapid app development, workflow logic, and SaaS launch fundamentals.',
        subjects: [
            'App prototyping tools',
            'Workflow automation',
            'Database logic design',
            'API connectors',
            'SaaS MVP building',
            'Payment gateway integration',
            'Drag-drop UI systems',
            'CRM app building',
            'Internal tool creation',
            'Scaling no-code apps',
            'SaaS monetization basics',
            'Deployment strategies',
        ],
        assessments: [
            'App prototyping tools',
            'Workflow automation',
            'Database logic design',
            'API connectors',
            'SaaS MVP building',
            'Payment gateway integration',
            'Drag-drop UI systems',
            'CRM app building',
            'Internal tool creation',
            'Scaling no-code apps',
            'SaaS monetization basics',
            'Deployment strategies',
        ],
    },
    {
        name: 'Advanced Excel and Business Intelligence',
        slug: 'advanced-excel-business-intelligence',
        description: 'Spreadsheet analytics, dashboarding, and BI decision support skills.',
        subjects: [
            'Power Query',
            'DAX formulas',
            'Pivot automation',
            'Dashboard storytelling',
            'Financial visualization',
            'Scenario managers',
            'Data cleaning workflows',
            'Excel macros overview',
            'KPI trackers',
            'Business reporting templates',
            'Data connectors',
            'Forecast modeling',
        ],
        assessments: [
            'Power Query',
            'DAX formulas',
            'Pivot automation',
            'Dashboard storytelling',
            'Financial visualization',
            'Scenario managers',
            'Data cleaning workflows',
            'Excel macros overview',
            'KPI trackers',
            'Business reporting templates',
            'Data connectors',
            'Forecast modeling',
        ],
    },
    {
        name: 'AR/VR and Spatial Computing',
        slug: 'ar-vr-spatial-computing',
        description: 'Extended reality concepts, interaction patterns, and spatial experience design.',
        subjects: [
            'Extended reality fundamentals',
            'Unity basics',
            'Immersive UX design',
            'VR commerce',
            'AR marketing campaigns',
            '3D environment creation',
            'Metaverse ecosystems',
            'Hardware overview',
            'Spatial UI patterns',
            'Industry applications',
            'Simulation design',
            'Ethical XR concerns',
        ],
        assessments: [
            'Extended reality fundamentals',
            'Unity basics',
            'Immersive UX design',
            'VR commerce',
            'AR marketing campaigns',
            '3D environment creation',
            'Metaverse ecosystems',
            'Hardware overview',
            'Spatial UI patterns',
            'Industry applications',
            'Simulation design',
            'Ethical XR concerns',
        ],
    },
    {
        name: 'HR Analytics and People Strategy',
        slug: 'hr-analytics-people-strategy',
        description: 'People analytics, workforce planning, and data-informed HR strategy.',
        subjects: [
            'Workforce analytics',
            'Talent acquisition metrics',
            'Employee lifecycle analysis',
            'Performance dashboards',
            'Predictive attrition models',
            'Compensation benchmarking',
            'Organizational design',
            'Engagement tracking',
            'Diversity metrics',
            'HR automation',
            'Learning analytics',
            'Strategic workforce planning',
        ],
        assessments: [
            'Workforce analytics',
            'Talent acquisition metrics',
            'Employee lifecycle analysis',
            'Performance dashboards',
            'Predictive attrition models',
            'Compensation benchmarking',
            'Organizational design',
            'Engagement tracking',
            'Diversity metrics',
            'HR automation',
            'Learning analytics',
            'Strategic workforce planning',
        ],
    },
    {
        name: 'Startup Incubation and Venture Building',
        slug: 'startup-incubation-venture-building',
        description: 'Startup creation, validation, fundraising, and operational scaling models.',
        subjects: [
            'Problem validation',
            'Lean experimentation',
            'Investor pitch decks',
            'Market sizing frameworks',
            'Fundraising strategies',
            'Cap table basics',
            'Go-to-market roadmap',
            'Startup finance basics',
            'Legal structuring overview',
            'Scaling operations',
            'Strategic partnerships',
            'Exit strategies',
        ],
        assessments: [
            'Problem validation',
            'Lean experimentation',
            'Investor pitch decks',
            'Market sizing frameworks',
            'Fundraising strategies',
            'Cap table basics',
            'Go-to-market roadmap',
            'Startup finance basics',
            'Legal structuring overview',
            'Scaling operations',
            'Strategic partnerships',
            'Exit strategies',
        ],
    },
    {
        name: 'AI in Healthcare and Biotech',
        slug: 'ai-healthcare-biotech',
        description: 'AI applications in healthcare systems, biotech workflows, and compliance.',
        subjects: [
            'AI diagnostics overview',
            'Medical data ethics',
            'Predictive patient modeling',
            'Health informatics',
            'Drug discovery AI',
            'Robotics in surgery',
            'Wearable health tech',
            'Telemedicine systems',
            'Clinical decision support',
            'Healthcare data privacy',
            'AI regulatory compliance',
            'Bioinformatics basics',
        ],
        assessments: [
            'AI diagnostics overview',
            'Medical data ethics',
            'Predictive patient modeling',
            'Health informatics',
            'Drug discovery AI',
            'Robotics in surgery',
            'Wearable health tech',
            'Telemedicine systems',
            'Clinical decision support',
            'Healthcare data privacy',
            'AI regulatory compliance',
            'Bioinformatics basics',
        ],
    },
    {
        name: 'Supply Chain and Logistics Analytics',
        slug: 'supply-chain-logistics-analytics',
        description: 'Data-driven logistics optimization, procurement analytics, and operations.',
        subjects: [
            'Demand forecasting',
            'Inventory optimization',
            'Logistics cost modeling',
            'Procurement analytics',
            'Warehouse automation',
            'ERP systems overview',
            'Risk mitigation strategies',
            'Global trade basics',
            'Route optimization',
            'Lean logistics',
            'KPI dashboards',
            'Supplier evaluation metrics',
        ],
        assessments: [
            'Demand forecasting',
            'Inventory optimization',
            'Logistics cost modeling',
            'Procurement analytics',
            'Warehouse automation',
            'ERP systems overview',
            'Risk mitigation strategies',
            'Global trade basics',
            'Route optimization',
            'Lean logistics',
            'KPI dashboards',
            'Supplier evaluation metrics',
        ],
    },
    {
        name: 'Emotional Intelligence for Leaders',
        slug: 'emotional-intelligence-leaders',
        description: 'Leadership communication, emotional regulation, and team influence systems.',
        subjects: [
            'Self-awareness frameworks',
            'Emotional regulation',
            'Conflict navigation',
            'Empathy development',
            'Influence psychology',
            'Feedback conversations',
            'Leadership presence',
            'Trust building',
            'Crisis communication',
            'Team motivation',
            'Decision psychology',
            'Resilience training',
        ],
        assessments: [
            'Self-awareness frameworks',
            'Emotional regulation',
            'Conflict navigation',
            'Empathy development',
            'Influence psychology',
            'Feedback conversations',
            'Leadership presence',
            'Trust building',
            'Crisis communication',
            'Team motivation',
            'Decision psychology',
            'Resilience training',
        ],
    },
    {
        name: 'AI-Powered Content Creation and Media Production',
        slug: 'ai-content-creation-media-production',
        description: 'AI media workflows for video, audio, distribution, and performance optimization.',
        subjects: [
            'AI video generation tools',
            'Script automation',
            'AI image generation ethics',
            'Voice cloning basics',
            'Podcast automation',
            'AI editing workflows',
            'Content repurposing systems',
            'SEO content scaling',
            'Thumbnail psychology',
            'Content performance analytics',
            'AI copyright concerns',
            'Multi-platform distribution',
        ],
        assessments: [
            'AI video generation tools',
            'Script automation',
            'AI image generation ethics',
            'Voice cloning basics',
            'Podcast automation',
            'AI editing workflows',
            'Content repurposing systems',
            'SEO content scaling',
            'Thumbnail psychology',
            'Content performance analytics',
            'AI copyright concerns',
            'Multi-platform distribution',
        ],
    },
] as const;
