type SourceQuestionLike = {
    question?: unknown;
    subtopic?: unknown;
    assessmentTitle?: unknown;
    options?: unknown;
    correctAnswer?: unknown;
    tags?: unknown;
};

type NormalizedSourceQuestion = {
    question: string;
    options: string[];
    tags: string[];
};

type QuestionQualityResult = {
    isUsable: boolean;
    reasons: string[];
};

const CONTINUATION_PREFIXES = [
    'demonstrates',
    'illustrates',
    'shows',
    'example of',
    'this is',
    'this demonstrates',
    'this illustrates',
    'this shows',
    'best action',
    'best approach',
    'likely cause',
    'main issue',
    'key issue',
    'action',
    'purpose',
    'benefit',
    'risk',
    'correct response',
    'correct approach',
    'ownership',
    'safe approach',
];

function cleanWhitespace(value: string): string {
    return value.replace(/\s+/g, ' ').trim();
}

function normalizeScenarioPrefix(value: string): string {
    return cleanWhitespace(value.replace(/(?:scenario:\s*){2,}/ig, 'Scenario: '));
}

function capitalizeSentence(value: string): string {
    const trimmed = cleanWhitespace(value);
    if (!trimmed) return '';
    return trimmed.charAt(0).toUpperCase() + trimmed.slice(1);
}

function wordCount(value: string): number {
    return cleanWhitespace(value).split(/\s+/).filter(Boolean).length;
}

function isNumericOnly(value: string): boolean {
    return /^\d+$/.test(cleanWhitespace(value));
}

function isContinuationFragment(value: string): boolean {
    const normalized = cleanWhitespace(value).toLowerCase();
    return CONTINUATION_PREFIXES.some((prefix) => normalized.startsWith(prefix));
}

function contextNeedsFollowUp(value: string): boolean {
    const normalized = cleanWhitespace(value).toLowerCase();
    return /(?:\bthis|\bwhich|\bwhat|\bwhy|\bhow|\blikely|\bbest|\bcorrect|\bsafest|\blegal|\bethical)\s*$/.test(normalized);
}

export function buildQuestionText(source: Pick<SourceQuestionLike, 'question' | 'subtopic' | 'assessmentTitle'>): string {
    const rawStem = cleanWhitespace(String(source.question || ''));
    const rawContext = cleanWhitespace(String(source.subtopic || source.assessmentTitle || ''));

    const stem = normalizeScenarioPrefix(rawStem);
    const context = normalizeScenarioPrefix(rawContext);

    if (!stem && context) {
        return capitalizeSentence(context);
    }

    if (isNumericOnly(stem) && context) {
        return capitalizeSentence(context);
    }

    if (!context) {
        return capitalizeSentence(stem);
    }

    const shouldMerge = isContinuationFragment(stem)
        || wordCount(stem) <= 3
        || contextNeedsFollowUp(context)
        || /^[a-z].*:\s*$/i.test(stem);

    if (!shouldMerge) {
        return capitalizeSentence(stem);
    }

    if (!stem) {
        return capitalizeSentence(context);
    }

    return cleanWhitespace(`${capitalizeSentence(context)} ${stem}`);
}

export function normalizeSourceQuestion(source: SourceQuestionLike): NormalizedSourceQuestion {
    return {
        question: buildQuestionText(source),
        options: Array.isArray(source.options)
            ? source.options.map((option) => cleanWhitespace(String(option || '')))
            : [],
        tags: Array.isArray(source.tags)
            ? source.tags.map((tag) => cleanWhitespace(String(tag || ''))).filter(Boolean)
            : [],
    };
}

export function evaluateQuestionQuality(source: SourceQuestionLike): QuestionQualityResult {
    const { question, options, tags } = normalizeSourceQuestion(source);
    const reasons: string[] = [];
    const normalizedQuestion = question.toLowerCase();
    const normalizedTags = tags.map((tag) => tag.toLowerCase());

    if (!question) {
        reasons.push('Question text is empty');
    }

    if (wordCount(question) < 4) {
        reasons.push('Question text is too short');
    }

    if ((question.match(/scenario:/gi) || []).length > 1) {
        reasons.push('Question repeats scenario prefix');
    }

    if (/\[(variant|duplicate)\s+\d+\]/i.test(question)) {
        reasons.push('Question contains synthetic variant suffix');
    }

    if (normalizedQuestion.includes('practice question')) {
        reasons.push('Question contains synthetic practice text');
    }

    if (normalizedTags.includes('autogenerated-fallback') || normalizedTags.includes('dummy')) {
        reasons.push('Question is tagged as autogenerated or dummy');
    }

    if (isNumericOnly(question)) {
        reasons.push('Question text is numeric only');
    }

    if (options.length !== 4 || options.some((option) => !option)) {
        reasons.push('Question does not have 4 non-empty options');
    }

    if (new Set(options.map((option) => option.toLowerCase())).size !== options.length) {
        reasons.push('Question contains duplicate options');
    }

    return {
        isUsable: reasons.length === 0,
        reasons,
    };
}
